// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongrunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class AuditManagerLogging: AuditManagerStub {
    let inner: any AuditManagerStub
    let logger: Logger

    public init(_ inner: any AuditManagerStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-auditmanager-v1"
      logger[metadataKey: "gcp.client.service"] = "auditmanager"
      logger[metadataKey: "gcp.experimental.swift.client"] = "AuditManager"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func enrollResource(
      request: EnrollResourceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.Enrollment {
      try await self._intercept(
        request: request,
        options: options,
        name: "enrollResource",
        action: {
          (r: EnrollResourceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAuditManagerV1.Enrollment
          in
          return try await self.inner.enrollResource(request: r, options: o)
        })
    }

    public func generateAuditScopeReport(
      request: GenerateAuditScopeReportRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.AuditScopeReport {
      try await self._intercept(
        request: request,
        options: options,
        name: "generateAuditScopeReport",
        action: {
          (r: GenerateAuditScopeReportRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAuditManagerV1.AuditScopeReport
          in
          return try await self.inner.generateAuditScopeReport(request: r, options: o)
        })
    }

    public func generateAuditReport(
      request: GenerateAuditReportRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "generateAuditReport",
        action: {
          (r: GenerateAuditReportRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.generateAuditReport(request: r, options: o)
        })
    }

    public func listAuditReports(
      request: ListAuditReportsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.ListAuditReportsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listAuditReports",
        action: {
          (r: ListAuditReportsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAuditManagerV1.ListAuditReportsResponse
          in
          return try await self.inner.listAuditReports(request: r, options: o)
        })
    }

    public func getAuditReport(
      request: GetAuditReportRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.AuditReport {
      try await self._intercept(
        request: request,
        options: options,
        name: "getAuditReport",
        action: {
          (r: GetAuditReportRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAuditManagerV1.AuditReport
          in
          return try await self.inner.getAuditReport(request: r, options: o)
        })
    }

    public func getResourceEnrollmentStatus(
      request: GetResourceEnrollmentStatusRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.ResourceEnrollmentStatus {
      try await self._intercept(
        request: request,
        options: options,
        name: "getResourceEnrollmentStatus",
        action: {
          (r: GetResourceEnrollmentStatusRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAuditManagerV1.ResourceEnrollmentStatus
          in
          return try await self.inner.getResourceEnrollmentStatus(request: r, options: o)
        })
    }

    public func listResourceEnrollmentStatuses(
      request: ListResourceEnrollmentStatusesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.ListResourceEnrollmentStatusesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listResourceEnrollmentStatuses",
        action: {
          (r: ListResourceEnrollmentStatusesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAuditManagerV1.ListResourceEnrollmentStatusesResponse
          in
          return try await self.inner.listResourceEnrollmentStatuses(request: r, options: o)
        })
    }

    public func listControls(
      request: ListControlsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.ListControlsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listControls",
        action: {
          (r: ListControlsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAuditManagerV1.ListControlsResponse
          in
          return try await self.inner.listControls(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongrunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongrunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongrunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongrunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongrunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongrunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
