// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  final class AuditManagerRetry: AuditManagerStub {
    let inner: any AuditManagerStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any AuditManagerStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func enrollResource(
      request: EnrollResourceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.Enrollment {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: EnrollResourceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAuditManagerV1.Enrollment
          in
          return try await self.inner.enrollResource(request: r, options: o)
        })
    }

    public func generateAuditScopeReport(
      request: GenerateAuditScopeReportRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.AuditScopeReport {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GenerateAuditScopeReportRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAuditManagerV1.AuditScopeReport
          in
          return try await self.inner.generateAuditScopeReport(request: r, options: o)
        })
    }

    public func generateAuditReport(
      request: GenerateAuditReportRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GenerateAuditReportRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.generateAuditReport(request: r, options: o)
        })
    }

    public func listAuditReports(
      request: ListAuditReportsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.ListAuditReportsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListAuditReportsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAuditManagerV1.ListAuditReportsResponse
          in
          return try await self.inner.listAuditReports(request: r, options: o)
        })
    }

    public func getAuditReport(
      request: GetAuditReportRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.AuditReport {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetAuditReportRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAuditManagerV1.AuditReport
          in
          return try await self.inner.getAuditReport(request: r, options: o)
        })
    }

    public func getResourceEnrollmentStatus(
      request: GetResourceEnrollmentStatusRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.ResourceEnrollmentStatus {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetResourceEnrollmentStatusRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAuditManagerV1.ResourceEnrollmentStatus
          in
          return try await self.inner.getResourceEnrollmentStatus(request: r, options: o)
        })
    }

    public func listResourceEnrollmentStatuses(
      request: ListResourceEnrollmentStatusesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.ListResourceEnrollmentStatusesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListResourceEnrollmentStatusesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAuditManagerV1.ListResourceEnrollmentStatusesResponse
          in
          return try await self.inner.listResourceEnrollmentStatuses(request: r, options: o)
        })
    }

    public func listControls(
      request: ListControlsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.ListControlsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListControlsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAuditManagerV1.ListControlsResponse
          in
          return try await self.inner.listControls(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
