// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongrunning
import GoogleRpc
import GoogleCloudGax

/// Service describing handlers for resources
///
/// @Snippet(path: "AuditManagerQuickstart")
public class AuditManagerClient: Clients.AuditManagerProtocol {
  let inner: any Clients.AuditManagerStub

  /// Creates a new `AuditManagerClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.AuditManagerStub = try Clients.AuditManagerTransport(options)
    inner = Clients.AuditManagerRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.AuditManagerLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Enrolls the customer resource(folder/project/organization) to the audit
  /// manager service by creating the audit managers Service Agent in customers
  /// workload and granting required permissions to the Service Agent. Please
  /// note that if enrollment request is made on the already enrolled workload
  /// then enrollment is executed overriding the existing set of destinations.
  ///
  /// @Snippet(path: "AuditManager_EnrollResource")
  public func enrollResource(
    request: EnrollResourceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAuditmanagerV1.Enrollment {
    try await self.inner.enrollResource(request: request, options: options)
  }

  /// Generates a demo report highlighting different responsibilities
  /// (Google/Customer/ shared) required to be fulfilled for the customer's
  /// workload to be compliant with the given standard.
  ///
  /// @Snippet(path: "AuditManager_GenerateAuditScopeReport")
  public func generateAuditScopeReport(
    request: GenerateAuditScopeReportRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAuditmanagerV1.AuditScopeReport {
    try await self.inner.generateAuditScopeReport(request: request, options: options)
  }

  /// Register the Audit Report generation requests and returns the OperationId
  /// using which the customer can track the report generation progress.
  ///
  /// @Snippet(path: "AuditManager_GenerateAuditReport")
  public func generateAuditReport(
    request: GenerateAuditReportRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.generateAuditReport(request: request, options: options)
  }

  /// Register the Audit Report generation requests and returns the OperationId
  /// using which the customer can track the report generation progress.
  ///
  /// @Snippet(path: "AuditManager_GenerateAuditReport")
  public func generateAuditReport(
    withPolling: GenerateAuditReportRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AuditReport> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<AuditReport>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try AuditReport(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.generateAuditReport(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AuditReport>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Lists audit reports in the selected parent scope
  ///
  /// @Snippet(path: "AuditManager_ListAuditReports")
  public func listAuditReports(
    request: ListAuditReportsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAuditmanagerV1.ListAuditReportsResponse {
    try await self.inner.listAuditReports(request: request, options: options)
  }

  /// Lists audit reports in the selected parent scope
  ///
  /// @Snippet(path: "AuditManager_ListAuditReports")
  public func listAuditReports(
    byItem: ListAuditReportsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<AuditReport, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAuditmanagerV1.ListAuditReportsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listAuditReports(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Get the overall audit report
  ///
  /// @Snippet(path: "AuditManager_GetAuditReport")
  public func getAuditReport(
    request: GetAuditReportRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAuditmanagerV1.AuditReport {
    try await self.inner.getAuditReport(request: request, options: options)
  }

  /// Get a resource along with its enrollment status.
  ///
  /// @Snippet(path: "AuditManager_GetResourceEnrollmentStatus")
  public func getResourceEnrollmentStatus(
    request: GetResourceEnrollmentStatusRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAuditmanagerV1.ResourceEnrollmentStatus {
    try await self.inner.getResourceEnrollmentStatus(request: request, options: options)
  }

  /// Fetches all resources under the parent along with their enrollment.
  ///
  /// @Snippet(path: "AuditManager_ListResourceEnrollmentStatuses")
  public func listResourceEnrollmentStatuses(
    request: ListResourceEnrollmentStatusesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAuditmanagerV1.ListResourceEnrollmentStatusesResponse {
    try await self.inner.listResourceEnrollmentStatuses(request: request, options: options)
  }

  /// Fetches all resources under the parent along with their enrollment.
  ///
  /// @Snippet(path: "AuditManager_ListResourceEnrollmentStatuses")
  public func listResourceEnrollmentStatuses(
    byItem: ListResourceEnrollmentStatusesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ResourceEnrollmentStatus, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudAuditmanagerV1.ListResourceEnrollmentStatusesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listResourceEnrollmentStatuses(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets controls needed to be implemented to be compliant to a standard.
  ///
  /// @Snippet(path: "AuditManager_ListControls")
  public func listControls(
    request: ListControlsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAuditmanagerV1.ListControlsResponse {
    try await self.inner.listControls(request: request, options: options)
  }

  /// Gets controls needed to be implemented to be compliant to a standard.
  ///
  /// @Snippet(path: "AuditManager_ListControls")
  public func listControls(
    byItem: ListControlsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Control, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAuditmanagerV1.ListControlsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listControls(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Lists information about the supported locations for this service.
  /// This method can be called in two ways:
  ///
  /// *   **List all public locations:** Use the path `GET /v1/locations`.
  /// *   **List project-visible locations:** Use the path
  /// `GET /v1/projects/{project_id}/locations`. This may include public
  /// locations as well as private or other locations specifically visible
  /// to the project.
  ///
  /// @Snippet(path: "AuditManager_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  /// This method can be called in two ways:
  ///
  /// *   **List all public locations:** Use the path `GET /v1/locations`.
  /// *   **List project-visible locations:** Use the path
  /// `GET /v1/projects/{project_id}/locations`. This may include public
  /// locations as well as private or other locations specifically visible
  /// to the project.
  ///
  /// @Snippet(path: "AuditManager_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "AuditManager_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "AuditManager_ListOperations")
  public func listOperations(
    request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "AuditManager_ListOperations")
  public func listOperations(
    byItem: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongrunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "AuditManager_GetOperation")
  func getOperation(
    request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "AuditManager_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongrunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "AuditManager_CancelOperation")
  public func cancelOperation(
    request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `AuditManagerClient`.
  ///
  /// To mock `AuditManagerClient` change your functions to receive
  /// `some AuditManagerProtocol` or `any AuditManagerProtocol`
  /// and pass a mock implementation in your tests.
  public protocol AuditManagerProtocol {
    /// See `AuditManagerClient.enrollResource`.
    func enrollResource(request: EnrollResourceRequest) async throws
      -> GoogleCloudAuditmanagerV1.Enrollment

    /// See `AuditManagerClient.enrollResource`.
    func enrollResource(
      scope: Swift.String,
      destinations: [EnrollResourceRequest.EligibleDestination],
    ) async throws -> GoogleCloudAuditmanagerV1.Enrollment

    /// See `AuditManagerClient.generateAuditScopeReport`.
    func generateAuditScopeReport(request: GenerateAuditScopeReportRequest) async throws
      -> GoogleCloudAuditmanagerV1.AuditScopeReport

    /// See `AuditManagerClient.generateAuditScopeReport`.
    func generateAuditScopeReport(
      scope: Swift.String,
      complianceStandard: Swift.String,
      reportFormat: GenerateAuditScopeReportRequest.AuditScopeReportFormat,
    ) async throws -> GoogleCloudAuditmanagerV1.AuditScopeReport

    /// See `AuditManagerClient.generateAuditReport`.
    func generateAuditReport(request: GenerateAuditReportRequest) async throws
      -> GoogleLongrunning.Operation

    /// See `AuditManagerClient.generateAuditReport`.
    func generateAuditReport(withPolling: GenerateAuditReportRequest) async throws
      -> any GoogleCloudGax.PollableOperation<AuditReport>

    /// See `AuditManagerClient.generateAuditReport`.
    func generateAuditReport(
      scope: Swift.String,
      gcsUri: Swift.String,
      complianceStandard: Swift.String,
      reportFormat: GenerateAuditReportRequest.AuditReportFormat,
    ) async throws -> any GoogleCloudGax.PollableOperation<AuditReport>

    /// See `AuditManagerClient.listAuditReports`.
    func listAuditReports(request: ListAuditReportsRequest) async throws
      -> GoogleCloudAuditmanagerV1.ListAuditReportsResponse

    /// See `AuditManagerClient.listAuditReports`.
    func listAuditReports(
      byItem: ListAuditReportsRequest
    ) throws -> any AsyncSequence<AuditReport, Swift.Error>

    /// See `AuditManagerClient.listAuditReports`.
    func listAuditReports(
      parent: Swift.String,
    ) throws -> any AsyncSequence<AuditReport, Swift.Error>

    /// See `AuditManagerClient.getAuditReport`.
    func getAuditReport(request: GetAuditReportRequest) async throws
      -> GoogleCloudAuditmanagerV1.AuditReport

    /// See `AuditManagerClient.getAuditReport`.
    func getAuditReport(
      name: Swift.String,
    ) async throws -> GoogleCloudAuditmanagerV1.AuditReport

    /// See `AuditManagerClient.getResourceEnrollmentStatus`.
    func getResourceEnrollmentStatus(request: GetResourceEnrollmentStatusRequest) async throws
      -> GoogleCloudAuditmanagerV1.ResourceEnrollmentStatus

    /// See `AuditManagerClient.getResourceEnrollmentStatus`.
    func getResourceEnrollmentStatus(
      name: Swift.String,
    ) async throws -> GoogleCloudAuditmanagerV1.ResourceEnrollmentStatus

    /// See `AuditManagerClient.listResourceEnrollmentStatuses`.
    func listResourceEnrollmentStatuses(request: ListResourceEnrollmentStatusesRequest) async throws
      -> GoogleCloudAuditmanagerV1.ListResourceEnrollmentStatusesResponse

    /// See `AuditManagerClient.listResourceEnrollmentStatuses`.
    func listResourceEnrollmentStatuses(
      byItem: ListResourceEnrollmentStatusesRequest
    ) throws -> any AsyncSequence<ResourceEnrollmentStatus, Swift.Error>

    /// See `AuditManagerClient.listResourceEnrollmentStatuses`.
    func listResourceEnrollmentStatuses(
      parent: Swift.String,
    ) throws -> any AsyncSequence<ResourceEnrollmentStatus, Swift.Error>

    /// See `AuditManagerClient.listControls`.
    func listControls(request: ListControlsRequest) async throws
      -> GoogleCloudAuditmanagerV1.ListControlsResponse

    /// See `AuditManagerClient.listControls`.
    func listControls(
      byItem: ListControlsRequest
    ) throws -> any AsyncSequence<Control, Swift.Error>

    /// See `AuditManagerClient.listControls`.
    func listControls(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Control, Swift.Error>

    /// See `AuditManagerClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `AuditManagerClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `AuditManagerClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `AuditManagerClient.listOperations`.
    func listOperations(request: GoogleLongrunning.ListOperationsRequest) async throws
      -> GoogleLongrunning.ListOperationsResponse

    /// See `AuditManagerClient.listOperations`.
    func listOperations(
      byItem: GoogleLongrunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

    /// See `AuditManagerClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

    /// See `AuditManagerClient.deleteOperation`.
    func deleteOperation(request: GoogleLongrunning.DeleteOperationRequest) async throws

    /// See `AuditManagerClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `AuditManagerClient.cancelOperation`.
    func cancelOperation(request: GoogleLongrunning.CancelOperationRequest) async throws

    /// See `AuditManagerClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `AuditManagerClient.enrollResource`.
    func enrollResource(
      request: EnrollResourceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAuditmanagerV1.Enrollment

    /// See `AuditManagerClient.generateAuditScopeReport`.
    func generateAuditScopeReport(
      request: GenerateAuditScopeReportRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAuditmanagerV1.AuditScopeReport

    /// See `AuditManagerClient.generateAuditReport`.
    func generateAuditReport(
      request: GenerateAuditReportRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `AuditManagerClient.generateAuditReport`.
    func generateAuditReport(
      withPolling: GenerateAuditReportRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<AuditReport>

    /// See `AuditManagerClient.listAuditReports`.
    func listAuditReports(
      request: ListAuditReportsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAuditmanagerV1.ListAuditReportsResponse

    /// See `AuditManagerClient.listAuditReports`.
    func listAuditReports(
      byItem: ListAuditReportsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<AuditReport, Swift.Error>

    /// See `AuditManagerClient.getAuditReport`.
    func getAuditReport(
      request: GetAuditReportRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAuditmanagerV1.AuditReport

    /// See `AuditManagerClient.getResourceEnrollmentStatus`.
    func getResourceEnrollmentStatus(
      request: GetResourceEnrollmentStatusRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAuditmanagerV1.ResourceEnrollmentStatus

    /// See `AuditManagerClient.listResourceEnrollmentStatuses`.
    func listResourceEnrollmentStatuses(
      request: ListResourceEnrollmentStatusesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAuditmanagerV1.ListResourceEnrollmentStatusesResponse

    /// See `AuditManagerClient.listResourceEnrollmentStatuses`.
    func listResourceEnrollmentStatuses(
      byItem: ListResourceEnrollmentStatusesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<ResourceEnrollmentStatus, Swift.Error>

    /// See `AuditManagerClient.listControls`.
    func listControls(
      request: ListControlsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAuditmanagerV1.ListControlsResponse

    /// See `AuditManagerClient.listControls`.
    func listControls(
      byItem: ListControlsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Control, Swift.Error>

    /// See `AuditManagerClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `AuditManagerClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `AuditManagerClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `AuditManagerClient.listOperations`.
    func listOperations(
      request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse

    /// See `AuditManagerClient.listOperations`.
    func listOperations(
      byItem: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

    /// See `AuditManagerClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongrunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `AuditManagerClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.AuditManagerProtocol {
  public func enrollResource(request: EnrollResourceRequest) async throws
    -> GoogleCloudAuditmanagerV1.Enrollment
  {
    try await self.enrollResource(request: request, options: .init())
  }

  public func enrollResource(
    request: EnrollResourceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAuditmanagerV1.Enrollment {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func enrollResource(
    scope: Swift.String,
    destinations: [EnrollResourceRequest.EligibleDestination],
  ) async throws -> GoogleCloudAuditmanagerV1.Enrollment {
    let request = EnrollResourceRequest().with {
      $0.scope = scope
      $0.destinations = destinations
    }
    return try await self.enrollResource(request: request)
  }

  public func generateAuditScopeReport(request: GenerateAuditScopeReportRequest) async throws
    -> GoogleCloudAuditmanagerV1.AuditScopeReport
  {
    try await self.generateAuditScopeReport(request: request, options: .init())
  }

  public func generateAuditScopeReport(
    request: GenerateAuditScopeReportRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAuditmanagerV1.AuditScopeReport {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func generateAuditScopeReport(
    scope: Swift.String,
    complianceStandard: Swift.String,
    reportFormat: GenerateAuditScopeReportRequest.AuditScopeReportFormat,
  ) async throws -> GoogleCloudAuditmanagerV1.AuditScopeReport {
    let request = GenerateAuditScopeReportRequest().with {
      $0.scope = scope
      $0.complianceStandard = complianceStandard
      $0.reportFormat = reportFormat
    }
    return try await self.generateAuditScopeReport(request: request)
  }

  public func generateAuditReport(request: GenerateAuditReportRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.generateAuditReport(request: request, options: .init())
  }

  public func generateAuditReport(
    request: GenerateAuditReportRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func generateAuditReport(withPolling: GenerateAuditReportRequest) async throws
    -> any GoogleCloudGax.PollableOperation<AuditReport>
  {
    try await self.generateAuditReport(withPolling: withPolling, options: .init())
  }

  public func generateAuditReport(
    withPolling: GenerateAuditReportRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AuditReport> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AuditReport>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func generateAuditReport(
    scope: Swift.String,
    gcsUri: Swift.String,
    complianceStandard: Swift.String,
    reportFormat: GenerateAuditReportRequest.AuditReportFormat,
  ) async throws -> any GoogleCloudGax.PollableOperation<AuditReport> {
    let request = GenerateAuditReportRequest().with {
      $0.scope = scope
      $0.destination = .gcsUri(gcsUri)
      $0.complianceStandard = complianceStandard
      $0.reportFormat = reportFormat
    }
    return try await self.generateAuditReport(withPolling: request)
  }

  public func listAuditReports(request: ListAuditReportsRequest) async throws
    -> GoogleCloudAuditmanagerV1.ListAuditReportsResponse
  {
    try await self.listAuditReports(request: request, options: .init())
  }

  public func listAuditReports(
    request: ListAuditReportsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAuditmanagerV1.ListAuditReportsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listAuditReports(
    byItem: ListAuditReportsRequest
  ) throws -> any AsyncSequence<AuditReport, Swift.Error> {
    try self.listAuditReports(byItem: byItem, options: .init())
  }

  public func listAuditReports(
    byItem: ListAuditReportsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<AuditReport, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAuditmanagerV1.ListAuditReportsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listAuditReports(
    parent: Swift.String,
  ) throws -> any AsyncSequence<AuditReport, Swift.Error> {
    let request = ListAuditReportsRequest().with {
      $0.parent = parent
    }
    return try self.listAuditReports(byItem: request)
  }

  public func getAuditReport(request: GetAuditReportRequest) async throws
    -> GoogleCloudAuditmanagerV1.AuditReport
  {
    try await self.getAuditReport(request: request, options: .init())
  }

  public func getAuditReport(
    request: GetAuditReportRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAuditmanagerV1.AuditReport {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getAuditReport(
    name: Swift.String,
  ) async throws -> GoogleCloudAuditmanagerV1.AuditReport {
    let request = GetAuditReportRequest().with {
      $0.name = name
    }
    return try await self.getAuditReport(request: request)
  }

  public func getResourceEnrollmentStatus(request: GetResourceEnrollmentStatusRequest) async throws
    -> GoogleCloudAuditmanagerV1.ResourceEnrollmentStatus
  {
    try await self.getResourceEnrollmentStatus(request: request, options: .init())
  }

  public func getResourceEnrollmentStatus(
    request: GetResourceEnrollmentStatusRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAuditmanagerV1.ResourceEnrollmentStatus {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getResourceEnrollmentStatus(
    name: Swift.String,
  ) async throws -> GoogleCloudAuditmanagerV1.ResourceEnrollmentStatus {
    let request = GetResourceEnrollmentStatusRequest().with {
      $0.name = name
    }
    return try await self.getResourceEnrollmentStatus(request: request)
  }

  public func listResourceEnrollmentStatuses(request: ListResourceEnrollmentStatusesRequest)
    async throws -> GoogleCloudAuditmanagerV1.ListResourceEnrollmentStatusesResponse
  {
    try await self.listResourceEnrollmentStatuses(request: request, options: .init())
  }

  public func listResourceEnrollmentStatuses(
    request: ListResourceEnrollmentStatusesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAuditmanagerV1.ListResourceEnrollmentStatusesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listResourceEnrollmentStatuses(
    byItem: ListResourceEnrollmentStatusesRequest
  ) throws -> any AsyncSequence<ResourceEnrollmentStatus, Swift.Error> {
    try self.listResourceEnrollmentStatuses(byItem: byItem, options: .init())
  }

  public func listResourceEnrollmentStatuses(
    byItem: ListResourceEnrollmentStatusesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ResourceEnrollmentStatus, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudAuditmanagerV1.ListResourceEnrollmentStatusesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listResourceEnrollmentStatuses(
    parent: Swift.String,
  ) throws -> any AsyncSequence<ResourceEnrollmentStatus, Swift.Error> {
    let request = ListResourceEnrollmentStatusesRequest().with {
      $0.parent = parent
    }
    return try self.listResourceEnrollmentStatuses(byItem: request)
  }

  public func listControls(request: ListControlsRequest) async throws
    -> GoogleCloudAuditmanagerV1.ListControlsResponse
  {
    try await self.listControls(request: request, options: .init())
  }

  public func listControls(
    request: ListControlsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAuditmanagerV1.ListControlsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listControls(
    byItem: ListControlsRequest
  ) throws -> any AsyncSequence<Control, Swift.Error> {
    try self.listControls(byItem: byItem, options: .init())
  }

  public func listControls(
    byItem: ListControlsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Control, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAuditmanagerV1.ListControlsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listControls(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Control, Swift.Error> {
    let request = ListControlsRequest().with {
      $0.parent = parent
    }
    return try self.listControls(byItem: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongrunning.ListOperationsRequest) async throws
    -> GoogleLongrunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongrunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongrunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let request = GoogleLongrunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongrunning.GetOperationRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongrunning.Operation {
    let request = GoogleLongrunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongrunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongrunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongrunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongrunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongrunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
