// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

public import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Audit scope report.
public struct AuditScopeReport: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. Name for the audit scope report, in one of the following
  /// formats:
  ///
  /// * `projects/{project}/locations/{location}/auditScopeReports/{audit_scope_report}`
  /// * `folders/{folder}/locations/{location}/auditScopeReports/{audit_scope_report}`
  /// * `organizations/{organization}/locations/{location}/auditScopeReports/{audit_scope_report}`
  public var name: Swift.String = Swift.String()

  /// Specific format or delivery method for the exported audit scope report.
  public var auditReport: OneOf_AuditReport? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AuditScopeReport`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AuditScopeReport().with { $0.scopeReportContents = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let scopeReportContents = CodingKeys(stringValue: "scopeReportContents")
    static let name = CodingKeys(stringValue: "name")

    static let _knownKeys: Set<Swift.String> = [
      "scopeReportContents",
      "name",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }

    var auditReport: OneOf_AuditReport? = nil
    let auditReportCheckAndSet = {
      if auditReport != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'auditReport'"))
      }
      auditReport = $0
    }
    if let scopeReportContents = try container.decodeIfPresent(
      Foundation.Data.self, forKey: .scopeReportContents)
    {
      try auditReportCheckAndSet(.scopeReportContents(scopeReportContents))
    }
    self.auditReport = auditReport
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)

    if let choice = self.auditReport {
      switch choice {
      case .scopeReportContents(let value):
        try container.encode(value, forKey: .scopeReportContents)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Specific format or delivery method for the exported audit scope report.
  public enum OneOf_AuditReport: Codable, Equatable, Sendable {
    /// Audit scope report content in byte format.
    case scopeReportContents(Foundation.Data)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.auditmanager.v1.AuditScopeReport"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
