// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// An audit report.
public struct AuditReport: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The name of this Audit Report, in the format of scope given in
  /// request.
  public var name: Swift.String = Swift.String()

  /// Output only. Report summary with compliance, violation counts etc.
  public var reportSummary: ReportSummary? = nil

  /// Output only. ClientOperationId
  public var operationId: Swift.String = Swift.String()

  /// Output only. The location where the generated report will be uploaded.
  public var destinationDetails: DestinationDetails? = nil

  /// Output only. Compliance Standard.
  public var complianceStandard: Swift.String = Swift.String()

  /// Output only. The parent scope on which the report was generated.
  public var scope: Swift.String = Swift.String()

  /// Output only. Creation time of the audit report.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The overall status of controls
  public var controlDetails: [ControlDetails] = []

  /// Output only. The state of Audit Report Generation.
  public var reportGenerationState: AuditReport.ReportGenerationState =
    AuditReport.ReportGenerationState()

  /// Output only. Compliance Framework of Audit Report
  public var complianceFramework: Swift.String = Swift.String()

  /// Output only. The ID/ Number for the scope on which the audit report was
  /// generated.
  public var scopeId: Swift.String = Swift.String()

  /// Initialize a new instance of `AuditReport`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AuditReport().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The different states of the Audit Manager report generation.
  public enum ReportGenerationState: Codable, Equatable, Sendable {
    /// Unspecified. Invalid state.
    case unspecified
    /// Audit report generation process is in progress, ie. operation state is
    /// neither OPERATION_STATE_DONE nor OPERATION_STATE_FAILED.
    case inProgress
    /// Audit report generation process is completed. Operation state is
    /// OPERATION_STATE_DONE.
    case completed
    /// Audit report generation process has failed. Operation state is
    /// OPERATION_STATE_FAILED.
    case failed
    /// Audit report generation process has completed. But report summary is
    /// unknown. This is valid for older reports.
    case summaryUnknown
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .inProgress: return 1
      case .completed: return 2
      case .failed: return 3
      case .summaryUnknown: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "REPORT_GENERATION_STATE_UNSPECIFIED"
      case .inProgress: return "IN_PROGRESS"
      case .completed: return "COMPLETED"
      case .failed: return "FAILED"
      case .summaryUnknown: return "SUMMARY_UNKNOWN"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "REPORT_GENERATION_STATE_UNSPECIFIED": self = .unspecified
      case "IN_PROGRESS": self = .inProgress
      case "COMPLETED": self = .completed
      case "FAILED": self = .failed
      case "SUMMARY_UNKNOWN": self = .summaryUnknown
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .inProgress
      case 2: self = .completed
      case 3: self = .failed
      case 4: self = .summaryUnknown
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .inProgress: return try container.encode(1)
      case .completed: return try container.encode(2)
      case .failed: return try container.encode(3)
      case .summaryUnknown: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.auditmanager.v1.AuditReport"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
