// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

/// Service describing handlers for resources
///
/// @Snippet(path: "AuditManagerQuickstart")
public final class AuditManagerClient: Clients.AuditManagerProtocol, Sendable {
  let inner: any Clients.AuditManagerStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `AuditManagerClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.AuditManagerStub = try Clients.AuditManagerTransport(options)
    inner = Clients.AuditManagerRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.AuditManagerLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Creates a new audit schedule in a given project and location.
  ///
  /// @Snippet(path: "AuditManager_CreateAuditSchedule")
  public func createAuditSchedule(
    request: CreateAuditScheduleRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAuditManagerV1.AuditSchedule {
    try await self.inner.createAuditSchedule(request: request, options: options)
  }

  /// Updates an existing audit schedule.
  ///
  /// @Snippet(path: "AuditManager_UpdateAuditSchedule")
  public func updateAuditSchedule(
    request: UpdateAuditScheduleRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAuditManagerV1.AuditSchedule {
    try await self.inner.updateAuditSchedule(request: request, options: options)
  }

  /// Gets details of a single audit schedule.
  ///
  /// @Snippet(path: "AuditManager_GetAuditSchedule")
  public func getAuditSchedule(
    request: GetAuditScheduleRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAuditManagerV1.AuditSchedule {
    try await self.inner.getAuditSchedule(request: request, options: options)
  }

  /// Lists audit schedules in a given project and location.
  ///
  /// @Snippet(path: "AuditManager_ListAuditSchedules")
  public func listAuditSchedules(
    request: ListAuditSchedulesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAuditManagerV1.ListAuditSchedulesResponse {
    try await self.inner.listAuditSchedules(request: request, options: options)
  }

  /// Lists audit schedules in a given project and location.
  ///
  /// @Snippet(path: "AuditManager_ListAuditSchedules")
  public func listAuditSchedules(
    byItem: ListAuditSchedulesRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<AuditSchedule, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAuditManagerV1.ListAuditSchedulesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listAuditSchedules(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Adds your project, folder, or organization to Audit
  /// Manager. This method creates the Audit Manager service agent in your
  /// workload and grants required permissions to the service agent.
  /// If you make this request on a workload that's already enrolled,
  /// then this method overrides the existing set of destinations.
  ///
  /// @Snippet(path: "AuditManager_EnrollResource")
  public func enrollResource(
    request: EnrollResourceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAuditManagerV1.Enrollment {
    try await self.inner.enrollResource(request: request, options: options)
  }

  /// Generates an audit scope report for the given standard.
  ///
  /// The report includes the following:
  ///
  /// * The technical attributes and constraints that Audit Manager uses to
  ///   verify your compliance with a framework.
  /// * A list of Google Cloud services and resources that are within the
  ///   scope of the framework.
  ///
  /// @Snippet(path: "AuditManager_GenerateAuditScopeReport")
  public func generateAuditScopeReport(
    request: GenerateAuditScopeReportRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAuditManagerV1.AuditScopeReport {
    try await self.inner.generateAuditScopeReport(request: request, options: options)
  }

  /// Registers audit report generation requests. This method returns the
  /// operation identifier that you can use to track the report generation
  /// progress.
  ///
  /// @Snippet(path: "AuditManager_GenerateAuditReport")
  public func generateAuditReport(
    request: GenerateAuditReportRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.generateAuditReport(request: request, options: options)
  }

  /// Registers audit report generation requests. This method returns the
  /// operation identifier that you can use to track the report generation
  /// progress.
  ///
  /// @Snippet(path: "AuditManager_GenerateAuditReport")
  public func generateAuditReport(
    withPolling: GenerateAuditReportRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AuditReport> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<AuditReport>.State in
      return try op._extractStatus(AuditReport.self)
    }
    let rawOp = try await self.generateAuditReport(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AuditReport>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists the audit reports for the organization, folder, or project that you
  /// specify as the parent scope.
  ///
  /// @Snippet(path: "AuditManager_ListAuditReports")
  public func listAuditReports(
    request: ListAuditReportsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAuditManagerV1.ListAuditReportsResponse {
    try await self.inner.listAuditReports(request: request, options: options)
  }

  /// Lists the audit reports for the organization, folder, or project that you
  /// specify as the parent scope.
  ///
  /// @Snippet(path: "AuditManager_ListAuditReports")
  public func listAuditReports(
    byItem: ListAuditReportsRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<AuditReport, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAuditManagerV1.ListAuditReportsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listAuditReports(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets the full metadata and findings for an audit report.
  ///
  /// @Snippet(path: "AuditManager_GetAuditReport")
  public func getAuditReport(
    request: GetAuditReportRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAuditManagerV1.AuditReport {
    try await self.inner.getAuditReport(request: request, options: options)
  }

  /// Gets a resource and its enrollment status.
  ///
  /// @Snippet(path: "AuditManager_GetResourceEnrollmentStatus")
  public func getResourceEnrollmentStatus(
    request: GetResourceEnrollmentStatusRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAuditManagerV1.ResourceEnrollmentStatus {
    try await self.inner.getResourceEnrollmentStatus(request: request, options: options)
  }

  /// Lists all the folders and projects in an organization or folder, along with
  /// their enrollments.
  ///
  /// @Snippet(path: "AuditManager_ListResourceEnrollmentStatuses")
  public func listResourceEnrollmentStatuses(
    request: ListResourceEnrollmentStatusesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAuditManagerV1.ListResourceEnrollmentStatusesResponse {
    try await self.inner.listResourceEnrollmentStatuses(request: request, options: options)
  }

  /// Lists all the folders and projects in an organization or folder, along with
  /// their enrollments.
  ///
  /// @Snippet(path: "AuditManager_ListResourceEnrollmentStatuses")
  public func listResourceEnrollmentStatuses(
    byItem: ListResourceEnrollmentStatusesRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<ResourceEnrollmentStatus, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudAuditManagerV1.ListResourceEnrollmentStatusesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listResourceEnrollmentStatuses(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Lists the controls that you must implement to become compliant to a
  /// regulatory standard.
  ///
  /// @Snippet(path: "AuditManager_ListControls")
  public func listControls(
    request: ListControlsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAuditManagerV1.ListControlsResponse {
    try await self.inner.listControls(request: request, options: options)
  }

  /// Lists the controls that you must implement to become compliant to a
  /// regulatory standard.
  ///
  /// @Snippet(path: "AuditManager_ListControls")
  public func listControls(
    byItem: ListControlsRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<Control, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAuditManagerV1.ListControlsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listControls(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "AuditManager_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "AuditManager_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "AuditManager_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AuditManager_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AuditManager_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AuditManager_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AuditManager_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AuditManager_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `AuditManagerClient`.
  ///
  /// To mock `AuditManagerClient` change your functions to receive
  /// `some AuditManagerProtocol` or `any AuditManagerProtocol`
  /// and pass a mock implementation in your tests.
  public protocol AuditManagerProtocol {
    /// See `AuditManagerClient.createAuditSchedule`.
    func createAuditSchedule(request: CreateAuditScheduleRequest) async throws
      -> GoogleCloudAuditManagerV1.AuditSchedule

    /// See `AuditManagerClient.createAuditSchedule`.
    func createAuditSchedule(
      parent: Swift.String,
      auditSchedule: AuditSchedule?,
      auditScheduleId: Swift.String,
    ) async throws -> GoogleCloudAuditManagerV1.AuditSchedule

    /// See `AuditManagerClient.updateAuditSchedule`.
    func updateAuditSchedule(request: UpdateAuditScheduleRequest) async throws
      -> GoogleCloudAuditManagerV1.AuditSchedule

    /// See `AuditManagerClient.updateAuditSchedule`.
    func updateAuditSchedule(
      auditSchedule: AuditSchedule?,
      updateMask: GoogleWKT.FieldMask?,
    ) async throws -> GoogleCloudAuditManagerV1.AuditSchedule

    /// See `AuditManagerClient.getAuditSchedule`.
    func getAuditSchedule(request: GetAuditScheduleRequest) async throws
      -> GoogleCloudAuditManagerV1.AuditSchedule

    /// See `AuditManagerClient.getAuditSchedule`.
    func getAuditSchedule(
      name: Swift.String,
    ) async throws -> GoogleCloudAuditManagerV1.AuditSchedule

    /// See `AuditManagerClient.listAuditSchedules`.
    func listAuditSchedules(request: ListAuditSchedulesRequest) async throws
      -> GoogleCloudAuditManagerV1.ListAuditSchedulesResponse

    /// See `AuditManagerClient.listAuditSchedules`.
    func listAuditSchedules(
      byItem: ListAuditSchedulesRequest
    ) throws -> any AsyncSequence<AuditSchedule, Swift.Error>

    /// See `AuditManagerClient.listAuditSchedules`.
    func listAuditSchedules(
      parent: Swift.String,
    ) throws -> any AsyncSequence<AuditSchedule, Swift.Error>

    /// See `AuditManagerClient.enrollResource`.
    func enrollResource(request: EnrollResourceRequest) async throws
      -> GoogleCloudAuditManagerV1.Enrollment

    /// See `AuditManagerClient.enrollResource`.
    func enrollResource(
      scope: Swift.String,
      destinations: [EnrollResourceRequest.EligibleDestination],
    ) async throws -> GoogleCloudAuditManagerV1.Enrollment

    /// See `AuditManagerClient.generateAuditScopeReport`.
    func generateAuditScopeReport(request: GenerateAuditScopeReportRequest) async throws
      -> GoogleCloudAuditManagerV1.AuditScopeReport

    /// See `AuditManagerClient.generateAuditScopeReport`.
    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    func generateAuditScopeReport(
      scope: Swift.String,
      complianceStandard: Swift.String,
      reportFormat: GenerateAuditScopeReportRequest.AuditScopeReportFormat,
    ) async throws -> GoogleCloudAuditManagerV1.AuditScopeReport

    /// See `AuditManagerClient.generateAuditReport`.
    func generateAuditReport(request: GenerateAuditReportRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `AuditManagerClient.generateAuditReport`.
    func generateAuditReport(withPolling: GenerateAuditReportRequest) async throws -> any GoogleGax
      .PollableOperation<AuditReport>

    /// See `AuditManagerClient.generateAuditReport`.
    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    func generateAuditReport(
      scope: Swift.String,
      gcsUri: Swift.String,
      complianceStandard: Swift.String,
      reportFormat: GenerateAuditReportRequest.AuditReportFormat,
    ) async throws -> any GoogleGax.PollableOperation<AuditReport>

    /// See `AuditManagerClient.listAuditReports`.
    func listAuditReports(request: ListAuditReportsRequest) async throws
      -> GoogleCloudAuditManagerV1.ListAuditReportsResponse

    /// See `AuditManagerClient.listAuditReports`.
    func listAuditReports(
      byItem: ListAuditReportsRequest
    ) throws -> any AsyncSequence<AuditReport, Swift.Error>

    /// See `AuditManagerClient.listAuditReports`.
    func listAuditReports(
      parent: Swift.String,
    ) throws -> any AsyncSequence<AuditReport, Swift.Error>

    /// See `AuditManagerClient.getAuditReport`.
    func getAuditReport(request: GetAuditReportRequest) async throws
      -> GoogleCloudAuditManagerV1.AuditReport

    /// See `AuditManagerClient.getAuditReport`.
    func getAuditReport(
      name: Swift.String,
    ) async throws -> GoogleCloudAuditManagerV1.AuditReport

    /// See `AuditManagerClient.getResourceEnrollmentStatus`.
    func getResourceEnrollmentStatus(request: GetResourceEnrollmentStatusRequest) async throws
      -> GoogleCloudAuditManagerV1.ResourceEnrollmentStatus

    /// See `AuditManagerClient.getResourceEnrollmentStatus`.
    func getResourceEnrollmentStatus(
      name: Swift.String,
    ) async throws -> GoogleCloudAuditManagerV1.ResourceEnrollmentStatus

    /// See `AuditManagerClient.listResourceEnrollmentStatuses`.
    func listResourceEnrollmentStatuses(request: ListResourceEnrollmentStatusesRequest) async throws
      -> GoogleCloudAuditManagerV1.ListResourceEnrollmentStatusesResponse

    /// See `AuditManagerClient.listResourceEnrollmentStatuses`.
    func listResourceEnrollmentStatuses(
      byItem: ListResourceEnrollmentStatusesRequest
    ) throws -> any AsyncSequence<ResourceEnrollmentStatus, Swift.Error>

    /// See `AuditManagerClient.listResourceEnrollmentStatuses`.
    func listResourceEnrollmentStatuses(
      parent: Swift.String,
    ) throws -> any AsyncSequence<ResourceEnrollmentStatus, Swift.Error>

    /// See `AuditManagerClient.listControls`.
    func listControls(request: ListControlsRequest) async throws
      -> GoogleCloudAuditManagerV1.ListControlsResponse

    /// See `AuditManagerClient.listControls`.
    func listControls(
      byItem: ListControlsRequest
    ) throws -> any AsyncSequence<Control, Swift.Error>

    /// See `AuditManagerClient.listControls`.
    func listControls(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Control, Swift.Error>

    /// See `AuditManagerClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `AuditManagerClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `AuditManagerClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `AuditManagerClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `AuditManagerClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `AuditManagerClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `AuditManagerClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `AuditManagerClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `AuditManagerClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `AuditManagerClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `AuditManagerClient.createAuditSchedule`.
    func createAuditSchedule(
      request: CreateAuditScheduleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.AuditSchedule

    /// See `AuditManagerClient.updateAuditSchedule`.
    func updateAuditSchedule(
      request: UpdateAuditScheduleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.AuditSchedule

    /// See `AuditManagerClient.getAuditSchedule`.
    func getAuditSchedule(
      request: GetAuditScheduleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.AuditSchedule

    /// See `AuditManagerClient.listAuditSchedules`.
    func listAuditSchedules(
      request: ListAuditSchedulesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.ListAuditSchedulesResponse

    /// See `AuditManagerClient.listAuditSchedules`.
    func listAuditSchedules(
      byItem: ListAuditSchedulesRequest, options: GoogleGax.RequestOptions
    ) throws -> any AsyncSequence<AuditSchedule, Swift.Error>

    /// See `AuditManagerClient.enrollResource`.
    func enrollResource(
      request: EnrollResourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.Enrollment

    /// See `AuditManagerClient.generateAuditScopeReport`.
    func generateAuditScopeReport(
      request: GenerateAuditScopeReportRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.AuditScopeReport

    /// See `AuditManagerClient.generateAuditReport`.
    func generateAuditReport(
      request: GenerateAuditReportRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AuditManagerClient.generateAuditReport`.
    func generateAuditReport(
      withPolling: GenerateAuditReportRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<AuditReport>

    /// See `AuditManagerClient.listAuditReports`.
    func listAuditReports(
      request: ListAuditReportsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.ListAuditReportsResponse

    /// See `AuditManagerClient.listAuditReports`.
    func listAuditReports(
      byItem: ListAuditReportsRequest, options: GoogleGax.RequestOptions
    ) throws -> any AsyncSequence<AuditReport, Swift.Error>

    /// See `AuditManagerClient.getAuditReport`.
    func getAuditReport(
      request: GetAuditReportRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.AuditReport

    /// See `AuditManagerClient.getResourceEnrollmentStatus`.
    func getResourceEnrollmentStatus(
      request: GetResourceEnrollmentStatusRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.ResourceEnrollmentStatus

    /// See `AuditManagerClient.listResourceEnrollmentStatuses`.
    func listResourceEnrollmentStatuses(
      request: ListResourceEnrollmentStatusesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.ListResourceEnrollmentStatusesResponse

    /// See `AuditManagerClient.listResourceEnrollmentStatuses`.
    func listResourceEnrollmentStatuses(
      byItem: ListResourceEnrollmentStatusesRequest, options: GoogleGax.RequestOptions
    ) throws -> any AsyncSequence<ResourceEnrollmentStatus, Swift.Error>

    /// See `AuditManagerClient.listControls`.
    func listControls(
      request: ListControlsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.ListControlsResponse

    /// See `AuditManagerClient.listControls`.
    func listControls(
      byItem: ListControlsRequest, options: GoogleGax.RequestOptions
    ) throws -> any AsyncSequence<Control, Swift.Error>

    /// See `AuditManagerClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `AuditManagerClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `AuditManagerClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `AuditManagerClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `AuditManagerClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `AuditManagerClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `AuditManagerClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.AuditManagerProtocol {
  public func createAuditSchedule(request: CreateAuditScheduleRequest) async throws
    -> GoogleCloudAuditManagerV1.AuditSchedule
  {
    try await self.createAuditSchedule(request: request, options: .init())
  }

  public func createAuditSchedule(
    request: CreateAuditScheduleRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAuditManagerV1.AuditSchedule {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createAuditSchedule(
    parent: Swift.String,
    auditSchedule: AuditSchedule?,
    auditScheduleId: Swift.String,
  ) async throws -> GoogleCloudAuditManagerV1.AuditSchedule {
    let request = CreateAuditScheduleRequest().with {
      $0.parent = parent
      $0.auditSchedule = auditSchedule
      $0.auditScheduleId = auditScheduleId
    }
    return try await self.createAuditSchedule(request: request)
  }

  public func updateAuditSchedule(request: UpdateAuditScheduleRequest) async throws
    -> GoogleCloudAuditManagerV1.AuditSchedule
  {
    try await self.updateAuditSchedule(request: request, options: .init())
  }

  public func updateAuditSchedule(
    request: UpdateAuditScheduleRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAuditManagerV1.AuditSchedule {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateAuditSchedule(
    auditSchedule: AuditSchedule?,
    updateMask: GoogleWKT.FieldMask?,
  ) async throws -> GoogleCloudAuditManagerV1.AuditSchedule {
    let request = UpdateAuditScheduleRequest().with {
      $0.auditSchedule = auditSchedule
      $0.updateMask = updateMask
    }
    return try await self.updateAuditSchedule(request: request)
  }

  public func getAuditSchedule(request: GetAuditScheduleRequest) async throws
    -> GoogleCloudAuditManagerV1.AuditSchedule
  {
    try await self.getAuditSchedule(request: request, options: .init())
  }

  public func getAuditSchedule(
    request: GetAuditScheduleRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAuditManagerV1.AuditSchedule {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getAuditSchedule(
    name: Swift.String,
  ) async throws -> GoogleCloudAuditManagerV1.AuditSchedule {
    let request = GetAuditScheduleRequest().with {
      $0.name = name
    }
    return try await self.getAuditSchedule(request: request)
  }

  public func listAuditSchedules(request: ListAuditSchedulesRequest) async throws
    -> GoogleCloudAuditManagerV1.ListAuditSchedulesResponse
  {
    try await self.listAuditSchedules(request: request, options: .init())
  }

  public func listAuditSchedules(
    request: ListAuditSchedulesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAuditManagerV1.ListAuditSchedulesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listAuditSchedules(
    byItem: ListAuditSchedulesRequest
  ) throws -> any AsyncSequence<AuditSchedule, Swift.Error> {
    try self.listAuditSchedules(byItem: byItem, options: .init())
  }

  public func listAuditSchedules(
    byItem: ListAuditSchedulesRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<AuditSchedule, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAuditManagerV1.ListAuditSchedulesResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listAuditSchedules(
    parent: Swift.String,
  ) throws -> any AsyncSequence<AuditSchedule, Swift.Error> {
    let request = ListAuditSchedulesRequest().with {
      $0.parent = parent
    }
    return try self.listAuditSchedules(byItem: request)
  }

  public func enrollResource(request: EnrollResourceRequest) async throws
    -> GoogleCloudAuditManagerV1.Enrollment
  {
    try await self.enrollResource(request: request, options: .init())
  }

  public func enrollResource(
    request: EnrollResourceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAuditManagerV1.Enrollment {
    throw GoogleGax.RequestError.unimplemented
  }

  public func enrollResource(
    scope: Swift.String,
    destinations: [EnrollResourceRequest.EligibleDestination],
  ) async throws -> GoogleCloudAuditManagerV1.Enrollment {
    let request = EnrollResourceRequest().with {
      $0.scope = scope
      $0.destinations = destinations
    }
    return try await self.enrollResource(request: request)
  }

  public func generateAuditScopeReport(request: GenerateAuditScopeReportRequest) async throws
    -> GoogleCloudAuditManagerV1.AuditScopeReport
  {
    try await self.generateAuditScopeReport(request: request, options: .init())
  }

  public func generateAuditScopeReport(
    request: GenerateAuditScopeReportRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAuditManagerV1.AuditScopeReport {
    throw GoogleGax.RequestError.unimplemented
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func generateAuditScopeReport(
    scope: Swift.String,
    complianceStandard: Swift.String,
    reportFormat: GenerateAuditScopeReportRequest.AuditScopeReportFormat,
  ) async throws -> GoogleCloudAuditManagerV1.AuditScopeReport {
    let request = GenerateAuditScopeReportRequest().with {
      $0.scope = scope
      $0.complianceStandard = complianceStandard
      $0.reportFormat = reportFormat
    }
    return try await self.generateAuditScopeReport(request: request)
  }

  public func generateAuditReport(request: GenerateAuditReportRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.generateAuditReport(request: request, options: .init())
  }

  public func generateAuditReport(
    request: GenerateAuditReportRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func generateAuditReport(withPolling: GenerateAuditReportRequest) async throws
    -> any GoogleGax.PollableOperation<AuditReport>
  {
    try await self.generateAuditReport(withPolling: withPolling, options: .init())
  }

  public func generateAuditReport(
    withPolling: GenerateAuditReportRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AuditReport> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AuditReport>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func generateAuditReport(
    scope: Swift.String,
    gcsUri: Swift.String,
    complianceStandard: Swift.String,
    reportFormat: GenerateAuditReportRequest.AuditReportFormat,
  ) async throws -> any GoogleGax.PollableOperation<AuditReport> {
    let request = GenerateAuditReportRequest().with {
      $0.scope = scope
      $0.destination = .gcsUri(gcsUri)
      $0.complianceStandard = complianceStandard
      $0.reportFormat = reportFormat
    }
    return try await self.generateAuditReport(withPolling: request)
  }

  public func listAuditReports(request: ListAuditReportsRequest) async throws
    -> GoogleCloudAuditManagerV1.ListAuditReportsResponse
  {
    try await self.listAuditReports(request: request, options: .init())
  }

  public func listAuditReports(
    request: ListAuditReportsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAuditManagerV1.ListAuditReportsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listAuditReports(
    byItem: ListAuditReportsRequest
  ) throws -> any AsyncSequence<AuditReport, Swift.Error> {
    try self.listAuditReports(byItem: byItem, options: .init())
  }

  public func listAuditReports(
    byItem: ListAuditReportsRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<AuditReport, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAuditManagerV1.ListAuditReportsResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listAuditReports(
    parent: Swift.String,
  ) throws -> any AsyncSequence<AuditReport, Swift.Error> {
    let request = ListAuditReportsRequest().with {
      $0.parent = parent
    }
    return try self.listAuditReports(byItem: request)
  }

  public func getAuditReport(request: GetAuditReportRequest) async throws
    -> GoogleCloudAuditManagerV1.AuditReport
  {
    try await self.getAuditReport(request: request, options: .init())
  }

  public func getAuditReport(
    request: GetAuditReportRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAuditManagerV1.AuditReport {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getAuditReport(
    name: Swift.String,
  ) async throws -> GoogleCloudAuditManagerV1.AuditReport {
    let request = GetAuditReportRequest().with {
      $0.name = name
    }
    return try await self.getAuditReport(request: request)
  }

  public func getResourceEnrollmentStatus(request: GetResourceEnrollmentStatusRequest) async throws
    -> GoogleCloudAuditManagerV1.ResourceEnrollmentStatus
  {
    try await self.getResourceEnrollmentStatus(request: request, options: .init())
  }

  public func getResourceEnrollmentStatus(
    request: GetResourceEnrollmentStatusRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAuditManagerV1.ResourceEnrollmentStatus {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getResourceEnrollmentStatus(
    name: Swift.String,
  ) async throws -> GoogleCloudAuditManagerV1.ResourceEnrollmentStatus {
    let request = GetResourceEnrollmentStatusRequest().with {
      $0.name = name
    }
    return try await self.getResourceEnrollmentStatus(request: request)
  }

  public func listResourceEnrollmentStatuses(request: ListResourceEnrollmentStatusesRequest)
    async throws -> GoogleCloudAuditManagerV1.ListResourceEnrollmentStatusesResponse
  {
    try await self.listResourceEnrollmentStatuses(request: request, options: .init())
  }

  public func listResourceEnrollmentStatuses(
    request: ListResourceEnrollmentStatusesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAuditManagerV1.ListResourceEnrollmentStatusesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listResourceEnrollmentStatuses(
    byItem: ListResourceEnrollmentStatusesRequest
  ) throws -> any AsyncSequence<ResourceEnrollmentStatus, Swift.Error> {
    try self.listResourceEnrollmentStatuses(byItem: byItem, options: .init())
  }

  public func listResourceEnrollmentStatuses(
    byItem: ListResourceEnrollmentStatusesRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<ResourceEnrollmentStatus, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudAuditManagerV1.ListResourceEnrollmentStatusesResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listResourceEnrollmentStatuses(
    parent: Swift.String,
  ) throws -> any AsyncSequence<ResourceEnrollmentStatus, Swift.Error> {
    let request = ListResourceEnrollmentStatusesRequest().with {
      $0.parent = parent
    }
    return try self.listResourceEnrollmentStatuses(byItem: request)
  }

  public func listControls(request: ListControlsRequest) async throws
    -> GoogleCloudAuditManagerV1.ListControlsResponse
  {
    try await self.listControls(request: request, options: .init())
  }

  public func listControls(
    request: ListControlsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAuditManagerV1.ListControlsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listControls(
    byItem: ListControlsRequest
  ) throws -> any AsyncSequence<Control, Swift.Error> {
    try self.listControls(byItem: byItem, options: .init())
  }

  public func listControls(
    byItem: ListControlsRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<Control, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAuditManagerV1.ListControlsResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listControls(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Control, Swift.Error> {
    let request = ListControlsRequest().with {
      $0.parent = parent
    }
    return try self.listControls(byItem: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
