// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol AuditManagerStub: Sendable {
    func createAuditSchedule(
      request: CreateAuditScheduleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.AuditSchedule

    func updateAuditSchedule(
      request: UpdateAuditScheduleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.AuditSchedule

    func getAuditSchedule(
      request: GetAuditScheduleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.AuditSchedule

    func listAuditSchedules(
      request: ListAuditSchedulesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.ListAuditSchedulesResponse

    func enrollResource(
      request: EnrollResourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.Enrollment

    func generateAuditScopeReport(
      request: GenerateAuditScopeReportRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.AuditScopeReport

    func generateAuditReport(
      request: GenerateAuditReportRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listAuditReports(
      request: ListAuditReportsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.ListAuditReportsResponse

    func getAuditReport(
      request: GetAuditReportRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.AuditReport

    func getResourceEnrollmentStatus(
      request: GetResourceEnrollmentStatusRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.ResourceEnrollmentStatus

    func listResourceEnrollmentStatuses(
      request: ListResourceEnrollmentStatusesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.ListResourceEnrollmentStatusesResponse

    func listControls(
      request: ListControlsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAuditManagerV1.ListControlsResponse

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
