// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An audit schedule, in one of the following formats:
///
/// * `projects/{project}/locations/{location}/auditSchedules/{audit_schedule}`
/// * `folders/{folder}/locations/{location}/auditSchedules/{audit_schedule}`
public struct AuditSchedule: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. Unique identifier for the audit schedule.
  /// Format:
  /// projects/{project}/locations/{location}/auditSchedules/{audit_schedule}
  /// folders/{folder}/locations/{location}/auditSchedules/{audit_schedule}
  /// organizations/{organization}/locations/{location}/auditSchedules/{audit_schedule}
  public var name: Swift.String = Swift.String()

  /// Optional. Display name for the audit schedule.
  public var displayName: Swift.String = Swift.String()

  /// Required. Cloud Storage bucket where Audit Manager can upload the audit
  /// report and evidence. The format is `gs://{bucket_name}`.
  public var gcsUri: Swift.String = Swift.String()

  /// Required. Framework (set of controls) that the audit scope report is
  /// generated against. For example, `NIST_800_53`.
  public var complianceFramework: Swift.String = Swift.String()

  /// Required. Format for the audit report.
  public var reportFormat: AuditSchedule.AuditReportFormat = AuditSchedule.AuditReportFormat()

  /// Required. Configuration that defines when and how often audit runs are
  /// automatically triggered for this schedule.
  public var scheduleConfig: ScheduleConfig? = nil

  /// Optional. State of the audit schedule. While most states are managed by the
  /// system, you can use
  /// [UpdateAuditSchedule][google.cloud.auditmanager.v1.AuditManager.UpdateAuditSchedule]
  /// to start, pause, or delete the schedule.
  ///
  /// [google.cloud.auditmanager.v1.AuditManager.UpdateAuditSchedule]: <doc:AuditManagerClient/updateAuditSchedule(request:options:)>
  public var state: ScheduleState = ScheduleState()

  /// Output only. Timestamp when the schedule was created.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. Timestamp when the schedule was last updated.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Output only. Calculated timestamp for the next scheduled run.
  public var nextRunTime: GoogleWKT.Timestamp? = nil

  /// Output only. Timestamp when the audit run was last triggered.
  public var lastTriggerTime: GoogleWKT.Timestamp? = nil

  /// Output only. Describes the error if the schedule is in an error state.
  public var errorMessage: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AuditSchedule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AuditSchedule().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let gcsUri = CodingKeys(stringValue: "gcsUri")
    static let complianceFramework = CodingKeys(stringValue: "complianceFramework")
    static let reportFormat = CodingKeys(stringValue: "reportFormat")
    static let scheduleConfig = CodingKeys(stringValue: "scheduleConfig")
    static let state = CodingKeys(stringValue: "state")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let nextRunTime = CodingKeys(stringValue: "nextRunTime")
    static let lastTriggerTime = CodingKeys(stringValue: "lastTriggerTime")
    static let errorMessage = CodingKeys(stringValue: "errorMessage")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "gcsUri",
      "complianceFramework",
      "reportFormat",
      "scheduleConfig",
      "state",
      "createTime",
      "updateTime",
      "nextRunTime",
      "lastTriggerTime",
      "errorMessage",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .gcsUri) {
      self.gcsUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .complianceFramework) {
      self.complianceFramework = value
    }
    if let value = try container.decodeIfPresent(
      AuditSchedule.AuditReportFormat.self, forKey: .reportFormat)
    {
      self.reportFormat = value
    }
    self.scheduleConfig = try container.decodeIfPresent(
      ScheduleConfig.self, forKey: .scheduleConfig)
    if let value = try container.decodeIfPresent(ScheduleState.self, forKey: .state) {
      self.state = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    self.nextRunTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .nextRunTime)
    self.lastTriggerTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .lastTriggerTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .errorMessage) {
      self.errorMessage = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.gcsUri, forKey: .gcsUri)
    try container.encode(self.complianceFramework, forKey: .complianceFramework)
    try container.encode(self.reportFormat, forKey: .reportFormat)
    try container.encodeIfPresent(self.scheduleConfig, forKey: .scheduleConfig)
    try container.encode(self.state, forKey: .state)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.nextRunTime, forKey: .nextRunTime)
    try container.encodeIfPresent(self.lastTriggerTime, forKey: .lastTriggerTime)
    try container.encode(self.errorMessage, forKey: .errorMessage)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Format for the audit report.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum AuditReportFormat: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// Open Document Format (ODF).
    case odf
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .odf: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "AUDIT_REPORT_FORMAT_UNSPECIFIED"
      case .odf: return "AUDIT_REPORT_FORMAT_ODF"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AuditReportFormat/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "AUDIT_REPORT_FORMAT_UNSPECIFIED": self = .unspecified
      case "AUDIT_REPORT_FORMAT_ODF": self = .odf
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AuditReportFormat/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .odf
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("AUDIT_REPORT_FORMAT_UNSPECIFIED")
      case .odf: return try container.encode("AUDIT_REPORT_FORMAT_ODF")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.auditmanager.v1.AuditSchedule"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
