// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Evaluation details for a control.
public struct ControlDetails: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Control that the findings are being reported for.
  public var control: Control? = nil

  /// Output only. Overall status of the findings for the control.
  public var complianceState: ComplianceState = ComplianceState()

  /// A control report summary that provides a high-level overview of the
  /// compliance controls and the assessment status.
  public var controlReportSummary: ReportSummary? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `ControlDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ControlDetails().with { $0.control = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let control = CodingKeys(stringValue: "control")
    static let complianceState = CodingKeys(stringValue: "complianceState")
    static let controlReportSummary = CodingKeys(stringValue: "controlReportSummary")

    static let _knownKeys: Set<Swift.String> = [
      "control",
      "complianceState",
      "controlReportSummary",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.control = try container.decodeIfPresent(Control.self, forKey: .control)
    if let value = try container.decodeIfPresent(ComplianceState.self, forKey: .complianceState) {
      self.complianceState = value
    }
    self.controlReportSummary = try container.decodeIfPresent(
      ReportSummary.self, forKey: .controlReportSummary)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.control, forKey: .control)
    try container.encode(self.complianceState, forKey: .complianceState)
    try container.encodeIfPresent(self.controlReportSummary, forKey: .controlReportSummary)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.auditmanager.v1.ControlDetails"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
