// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for
/// [CreateAuditSchedule][google.cloud.auditmanager.v1.AuditManager.CreateAuditSchedule].
///
/// [google.cloud.auditmanager.v1.AuditManager.CreateAuditSchedule]: <doc:AuditManagerClient/createAuditSchedule(request:options:)>
public struct CreateAuditScheduleRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Project or folder that this audit schedule is for, in one of the
  /// following formats:
  ///
  /// * `projects/{project}/locations/{location}`
  /// * `folders/{folder}/locations/{location}`
  public var parent: Swift.String = Swift.String()

  /// Required. Audit schedule to create.
  public var auditSchedule: AuditSchedule? = nil

  /// Required. ID to use for the audit schedule, which becomes the final
  /// component of the audit schedule's resource name.
  public var auditScheduleId: Swift.String = Swift.String()

  /// Optional. If `true`, only validates the request and does not create the
  /// audit schedule. This executes standard request validation (such as schema,
  /// framework existence, scope, and IAM checks) and skips the apply phase.
  ///
  /// Use this field for the following purposes:
  /// * **Infrastructure as Code (IaC)**: Allow tools like Terraform to run
  ///   dry-run mutations (e.g., `terraform plan`) without creating real
  ///   resources or incurring costs.
  /// * **User Interface Validation**: Enable real-time form and permission
  ///   validation in custom UIs before submitting requests.
  /// * **CI/CD & Automation**: Test your scripts, permissions, and parameters
  ///   safely without consuming resource quotas.
  public var validateOnly: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CreateAuditScheduleRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateAuditScheduleRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let auditSchedule = CodingKeys(stringValue: "auditSchedule")
    static let auditScheduleId = CodingKeys(stringValue: "auditScheduleId")
    static let validateOnly = CodingKeys(stringValue: "validateOnly")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "auditSchedule",
      "auditScheduleId",
      "validateOnly",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    self.auditSchedule = try container.decodeIfPresent(AuditSchedule.self, forKey: .auditSchedule)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .auditScheduleId) {
      self.auditScheduleId = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .validateOnly) {
      self.validateOnly = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encodeIfPresent(self.auditSchedule, forKey: .auditSchedule)
    try container.encode(self.auditScheduleId, forKey: .auditScheduleId)
    try container.encode(self.validateOnly, forKey: .validateOnly)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.auditmanager.v1.CreateAuditScheduleRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
