// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for
/// [EnrollResource][google.cloud.auditmanager.v1.AuditManager.EnrollResource].
///
/// [google.cloud.auditmanager.v1.AuditManager.EnrollResource]: <doc:AuditManagerClient/enrollResource(request:options:)>
public struct EnrollResourceRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Organization, folder, or project to enroll in Audit Manager, in
  /// one of the following formats:
  ///
  /// * `projects/{project}/locations/{location}`
  /// * `folders/{folder}/locations/{location}`
  /// * `organizations/{organization}/locations/{location}`
  public var scope: Swift.String = Swift.String()

  /// Required. Cloud Storage buckets that you can upload your audit reports to
  /// during the audit process.
  ///
  /// When you enroll an organization or folder, you can choose a Cloud Storage
  /// bucket from any project in the organization or folder. If you run an audit
  /// at the project level using the service agent at the organization or folder
  /// level, all the buckets that are associated with the service agent are
  /// available.
  public var destinations: [EnrollResourceRequest.EligibleDestination] = []

  /// Initialize a new instance of `EnrollResourceRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EnrollResourceRequest().with { $0.scope = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Details about the bucket where you want to upload the audit report.
  public struct EligibleDestination: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Available Cloud Storage buckets.
    public var eligibleDestinations: OneOf_EligibleDestinations? = nil

    /// Initialize a new instance of `EligibleDestination`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = EligibleDestination().with { $0.eligibleGcsBucket = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case eligibleGcsBucket = "eligibleGcsBucket"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var eligibleDestinations: OneOf_EligibleDestinations? = nil
      let eligibleDestinationsCheckAndSet = {
        if eligibleDestinations != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'eligibleDestinations'"))
        }
        eligibleDestinations = $0
      }
      if let eligibleGcsBucket = try container.decodeIfPresent(
        Swift.String.self, forKey: .eligibleGcsBucket)
      {
        try eligibleDestinationsCheckAndSet(.eligibleGcsBucket(eligibleGcsBucket))
      }
      self.eligibleDestinations = eligibleDestinations
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.eligibleDestinations {
        switch choice {
        case .eligibleGcsBucket(let value):
          try container.encode(value, forKey: .eligibleGcsBucket)
        }
      }
    }

    /// Available Cloud Storage buckets.
    public enum OneOf_EligibleDestinations: Codable, Equatable, Sendable {
      /// The location of the Cloud Storage bucket where you want to upload the
      /// audit report and evidence during the
      /// [GenerateAuditReport][google.cloud.auditmanager.v1.AuditManager.GenerateAuditReport]
      /// API call.
      ///
      /// [google.cloud.auditmanager.v1.AuditManager.GenerateAuditReport]: <doc:AuditManagerClient/generateAuditReport(request:options:)>
      case eligibleGcsBucket(Swift.String)
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.auditmanager.v1.EnrollResourceRequest.EligibleDestination"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.auditmanager.v1.EnrollResourceRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
