// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Request message for
/// [EnrollResource][google.cloud.auditmanager.v1.AuditManager.EnrollResource].
///
/// [google.cloud.auditmanager.v1.AuditManager.EnrollResource]: <doc:AuditManagerClient/enrollResource(request:options:)>
public struct EnrollResourceRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Organization, folder, or project to enroll in Audit Manager, in
  /// one of the following formats:
  ///
  /// * `projects/{project}/locations/{location}`
  /// * `folders/{folder}/locations/{location}`
  /// * `organizations/{organization}/locations/{location}`
  public var scope: Swift.String = Swift.String()

  /// Required. Cloud Storage buckets that you can upload your audit reports to
  /// during the audit process.
  ///
  /// When you enroll an organization or folder, you can choose a Cloud Storage
  /// bucket from any project in the organization or folder. If you run an audit
  /// at the project level using the service agent at the organization or folder
  /// level, all the buckets that are associated with the service agent are
  /// available.
  public var destinations: [EnrollResourceRequest.EligibleDestination] = []

  /// Optional. If `true`, only validates the request and does not enroll the
  /// resource. This executes standard request validation (such as schema, IAM,
  /// and destination checks) and skips the apply phase.
  ///
  /// Use this field for the following purposes:
  /// * **Infrastructure as Code (IaC)**: Allow tools like Terraform to run
  ///   dry-run mutations (e.g., `terraform plan`) without creating real
  ///   resources or incurring costs.
  /// * **User Interface Validation**: Enable real-time form and permission
  ///   validation in custom UIs before submitting requests.
  /// * **CI/CD & Automation**: Test your scripts, permissions, and parameters
  ///   safely without consuming resource quotas.
  public var validateOnly: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `EnrollResourceRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EnrollResourceRequest().with { $0.scope = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let scope = CodingKeys(stringValue: "scope")
    static let destinations = CodingKeys(stringValue: "destinations")
    static let validateOnly = CodingKeys(stringValue: "validateOnly")

    static let _knownKeys: Set<Swift.String> = [
      "scope",
      "destinations",
      "validateOnly",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .scope) {
      self.scope = value
    }
    if let value = try container.decodeIfPresent(
      [EnrollResourceRequest.EligibleDestination].self, forKey: .destinations)
    {
      self.destinations = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .validateOnly) {
      self.validateOnly = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.scope, forKey: .scope)
    try container.encode(self.destinations, forKey: .destinations)
    try container.encode(self.validateOnly, forKey: .validateOnly)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Details about the bucket where you want to upload the audit report.
  public struct EligibleDestination: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Available Cloud Storage buckets.
    public var eligibleDestinations: OneOf_EligibleDestinations? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `EligibleDestination`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = EligibleDestination().with { $0.eligibleGcsBucket = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let eligibleGcsBucket = CodingKeys(stringValue: "eligibleGcsBucket")

      static let _knownKeys: Set<Swift.String> = [
        "eligibleGcsBucket"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var eligibleDestinations: OneOf_EligibleDestinations? = nil
      let eligibleDestinationsCheckAndSet = {
        if eligibleDestinations != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'eligibleDestinations'"))
        }
        eligibleDestinations = $0
      }
      if let eligibleGcsBucket = try container.decodeIfPresent(
        Swift.String.self, forKey: .eligibleGcsBucket)
      {
        try eligibleDestinationsCheckAndSet(.eligibleGcsBucket(eligibleGcsBucket))
      }
      self.eligibleDestinations = eligibleDestinations
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.eligibleDestinations {
        switch choice {
        case .eligibleGcsBucket(let value):
          try container.encode(value, forKey: .eligibleGcsBucket)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Available Cloud Storage buckets.
    public enum OneOf_EligibleDestinations: Codable, Equatable, Sendable {
      /// The location of the Cloud Storage bucket where you want to upload the
      /// audit report and evidence during the
      /// [GenerateAuditReport][google.cloud.auditmanager.v1.AuditManager.GenerateAuditReport]
      /// API call.
      ///
      /// [google.cloud.auditmanager.v1.AuditManager.GenerateAuditReport]: <doc:AuditManagerClient/generateAuditReport(request:options:)>
      case eligibleGcsBucket(Swift.String)
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.auditmanager.v1.EnrollResourceRequest.EligibleDestination"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.auditmanager.v1.EnrollResourceRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
