// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for
/// [GenerateAuditReport][google.cloud.auditmanager.v1.AuditManager.GenerateAuditReport].
///
/// [google.cloud.auditmanager.v1.AuditManager.GenerateAuditReport]: <doc:AuditManagerClient/generateAuditReport(request:options:)>
public struct GenerateAuditReportRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Organization, folder, or project that the audit applies to, in
  /// one of the following formats:
  ///
  /// * `projects/{project}/locations/{location}`
  /// * `folders/{folder}/locations/{location}`
  /// * `organizations/{organization}/locations/{location}`
  public var scope: Swift.String = Swift.String()

  /// Optional. Deprecated. Compliance standard for the audit report.
  ///
  /// Use the `compliance_framework` field instead.
  @available(*, deprecated)
  public var complianceStandard: Swift.String = Swift.String()

  /// Required. Format for the audit report.
  public var reportFormat: GenerateAuditReportRequest.AuditReportFormat =
    GenerateAuditReportRequest.AuditReportFormat()

  /// Required. The framework that's used for the audit report. For example,
  /// `NIST_800_53`.
  public var complianceFramework: Swift.String = Swift.String()

  /// Optional. If `true`, only validates the request and does not generate the
  /// audit report. This executes standard request validation (such as schema,
  /// framework existence, scope, and IAM checks) and skips the apply phase.
  ///
  /// Use this field for the following purposes:
  /// * **Infrastructure as Code (IaC)**: Allow tools like Terraform to run
  ///   dry-run mutations (e.g., `terraform plan`) without creating real
  ///   resources or incurring costs.
  /// * **User Interface Validation**: Enable real-time form and permission
  ///   validation in custom UIs before submitting requests.
  /// * **CI/CD & Automation**: Test your scripts, permissions, and parameters
  ///   safely without triggering expensive Long-Running Operations (LROs) or
  ///   consuming resource quotas.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// Options for the report destination location.
  public var destination: OneOf_Destination? = nil

  /// Initialize a new instance of `GenerateAuditReportRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GenerateAuditReportRequest().with { $0.gcsUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case gcsUri = "gcsUri"
    case scope = "scope"
    case complianceStandard = "complianceStandard"
    case reportFormat = "reportFormat"
    case complianceFramework = "complianceFramework"
    case validateOnly = "validateOnly"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.scope = try container.decode(Swift.String.self, forKey: .scope)
    self.complianceStandard = try container.decode(Swift.String.self, forKey: .complianceStandard)
    self.reportFormat = try container.decode(
      GenerateAuditReportRequest.AuditReportFormat.self, forKey: .reportFormat)
    self.complianceFramework = try container.decode(Swift.String.self, forKey: .complianceFramework)
    self.validateOnly = try container.decode(Swift.Bool.self, forKey: .validateOnly)

    var destination: OneOf_Destination? = nil
    let destinationCheckAndSet = {
      if destination != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'destination'"))
      }
      destination = $0
    }
    if let gcsUri = try container.decodeIfPresent(Swift.String.self, forKey: .gcsUri) {
      try destinationCheckAndSet(.gcsUri(gcsUri))
    }
    self.destination = destination
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.scope, forKey: .scope)
    try container.encode(self.complianceStandard, forKey: .complianceStandard)
    try container.encode(self.reportFormat, forKey: .reportFormat)
    try container.encode(self.complianceFramework, forKey: .complianceFramework)
    try container.encode(self.validateOnly, forKey: .validateOnly)

    if let choice = self.destination {
      switch choice {
      case .gcsUri(let value):
        try container.encode(value, forKey: .gcsUri)
      }
    }
  }

  /// Format for the audit report.
  public enum AuditReportFormat: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// Open Document format.
    case odf
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .odf: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "AUDIT_REPORT_FORMAT_UNSPECIFIED"
      case .odf: return "AUDIT_REPORT_FORMAT_ODF"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AuditReportFormat/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "AUDIT_REPORT_FORMAT_UNSPECIFIED": self = .unspecified
      case "AUDIT_REPORT_FORMAT_ODF": self = .odf
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AuditReportFormat/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .odf
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .odf: return try container.encode(1)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Options for the report destination location.
  public enum OneOf_Destination: Codable, Equatable, Sendable {
    /// URL for the Cloud Storage bucket where the report and evidence is
    /// uploaded. You must select a bucket that was provided during the
    /// enrollment process.
    case gcsUri(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.auditmanager.v1.GenerateAuditReportRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
