// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Message for requesting the Audit Report.
public struct GenerateAuditReportRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Scope for which the AuditScopeReport is required. Must be of
  /// format resource_type/resource_identifier Eg:
  /// projects/{project}/locations/{location},
  /// folders/{folder}/locations/{location}
  public var scope: Swift.String = Swift.String()

  /// Required. Compliance Standard against which the Scope Report must be
  /// generated. Eg: FEDRAMP_MODERATE
  public var complianceStandard: Swift.String = Swift.String()

  /// Required. The format in which the audit report should be created.
  public var reportFormat: GenerateAuditReportRequest.AuditReportFormat =
    GenerateAuditReportRequest.AuditReportFormat()

  /// Required. Compliance framework against which the Report must be generated.
  public var complianceFramework: Swift.String = Swift.String()

  /// Set of options for the report destination location.
  public var destination: OneOf_Destination? = nil

  /// Initialize a new instance of `GenerateAuditReportRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GenerateAuditReportRequest().with { $0.gcsUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case gcsUri = "gcsUri"
    case scope = "scope"
    case complianceStandard = "complianceStandard"
    case reportFormat = "reportFormat"
    case complianceFramework = "complianceFramework"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.scope = try container.decode(Swift.String.self, forKey: .scope)
    self.complianceStandard = try container.decode(Swift.String.self, forKey: .complianceStandard)
    self.reportFormat = try container.decode(
      GenerateAuditReportRequest.AuditReportFormat.self, forKey: .reportFormat)
    self.complianceFramework = try container.decode(Swift.String.self, forKey: .complianceFramework)

    var destination: OneOf_Destination? = nil
    let destinationCheckAndSet = {
      if destination != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'destination'"))
      }
      destination = $0
    }
    if let gcsUri = try container.decodeIfPresent(Swift.String.self, forKey: .gcsUri) {
      try destinationCheckAndSet(.gcsUri(gcsUri))
    }
    self.destination = destination
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.scope, forKey: .scope)
    try container.encode(self.complianceStandard, forKey: .complianceStandard)
    try container.encode(self.reportFormat, forKey: .reportFormat)
    try container.encode(self.complianceFramework, forKey: .complianceFramework)

    if let choice = self.destination {
      switch choice {
      case .gcsUri(let value):
        try container.encode(value, forKey: .gcsUri)
      }
    }
  }

  /// The options for the audit report format.
  public enum AuditReportFormat: Codable, Equatable, Sendable {
    /// Unspecified. Invalid state.
    case unspecified
    /// Audit Report creation format is Open Document.
    case odf
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .odf: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "AUDIT_REPORT_FORMAT_UNSPECIFIED"
      case .odf: return "AUDIT_REPORT_FORMAT_ODF"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "AUDIT_REPORT_FORMAT_UNSPECIFIED": self = .unspecified
      case "AUDIT_REPORT_FORMAT_ODF": self = .odf
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .odf
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .odf: return try container.encode(1)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Set of options for the report destination location.
  public enum OneOf_Destination: Codable, Equatable, Sendable {
    /// Destination Cloud storage bucket where report and evidence must be
    /// uploaded. The Cloud storage bucket provided here must be selected among
    /// the buckets entered during the enrollment process.
    case gcsUri(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.auditmanager.v1.GenerateAuditReportRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
