// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [ListResourceEnrollmentStatuses][google.cloud.auditmanager.v1.AuditManager.ListResourceEnrollmentStatuses].
///
/// [google.cloud.auditmanager.v1.AuditManager.ListResourceEnrollmentStatuses]: <doc:AuditManagerClient/listResourceEnrollmentStatuses(request:)>
public struct ListResourceEnrollmentStatusesRequest: Codable, Equatable, GoogleCloudWkt
    ._AnyPackable,
  Sendable
{
  /// Required. Parent organization or folder to list enrollment statuses for,
  /// in one of the following formats:
  ///
  /// * `folders/{folder}/locations/{location}`
  /// * `organizations/{organization}/locations/{location}`
  public var parent: Swift.String = Swift.String()

  /// Optional. Maximum number of items to return in a single page. The service
  /// might return fewer items than this value. If unspecified, the service picks
  /// an appropriate default. The maximum value is 100; values above 100 are
  /// reduced to 100.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A page token, received from a previous call, to retrieve the next
  /// page of results.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListResourceEnrollmentStatusesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListResourceEnrollmentStatusesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.auditmanager.v1.ListResourceEnrollmentStatusesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
