// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudGax
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Response message for
/// [ListAuditReports][google.cloud.auditmanager.v1.AuditManager.ListAuditReports].
///
/// [google.cloud.auditmanager.v1.AuditManager.ListAuditReports]: <doc:AuditManagerClient/listAuditReports(request:options:)>
public struct ListAuditReportsResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  GoogleCloudGax._PaginatedResponse,
  Sendable
{
  /// Output only. Audit reports.
  public var auditReports: [AuditReport] = []

  /// Output only. A token that you can send as the `page_token` in a subsequent
  /// request to retrieve the next page of results. If this field is empty, there
  /// are no subsequent pages.
  public var nextPageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListAuditReportsResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListAuditReportsResponse().with { $0.auditReports = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.auditmanager.v1.ListAuditReportsResponse"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }

  public func _getPaginatedItems() -> [AuditReport] {
    return self.auditReports
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
