// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Details about the current status of the report-generation process.
public struct ReportGenerationProgress: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. Current state of execution for report generation.
  public var state: OperationState = OperationState()

  /// Output only. Reason for failure during the audit report generation process.
  /// This field is set only if the `OperationState` attribute is
  /// `OPERATION_STATE_FAILED`.
  public var failureReason: Swift.String = Swift.String()

  /// Progress of the evaluation process. The progress is
  /// defined in terms of percentage complete.
  public var evaluationPercentComplete: Swift.Double = Swift.Double()

  /// Report generation progress, defined in terms of percentage complete.
  /// Until evaluation is complete, this value is always `0`.
  public var reportGenerationPercentComplete: Swift.Double = Swift.Double()

  /// Report uploading progress, defined in terms of percentage complete.
  /// Until evaluation and report generation are complete, this value is always
  /// `0`.
  public var reportUploadingPercentComplete: Swift.Double = Swift.Double()

  /// Output only. Cloud Storage bucket where the audit report is uploaded to
  /// after the evaluation process is completed.
  public var destinationGcsBucket: Swift.String = Swift.String()

  /// Output only. Name of the audit report.
  public var auditReport: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `ReportGenerationProgress`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReportGenerationProgress().with { $0.state = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let state = CodingKeys(stringValue: "state")
    static let failureReason = CodingKeys(stringValue: "failureReason")
    static let evaluationPercentComplete = CodingKeys(stringValue: "evaluationPercentComplete")
    static let reportGenerationPercentComplete = CodingKeys(
      stringValue: "reportGenerationPercentComplete")
    static let reportUploadingPercentComplete = CodingKeys(
      stringValue: "reportUploadingPercentComplete")
    static let destinationGcsBucket = CodingKeys(stringValue: "destinationGcsBucket")
    static let auditReport = CodingKeys(stringValue: "auditReport")

    static let _knownKeys: Set<Swift.String> = [
      "state",
      "failureReason",
      "evaluationPercentComplete",
      "reportGenerationPercentComplete",
      "reportUploadingPercentComplete",
      "destinationGcsBucket",
      "auditReport",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(OperationState.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .failureReason) {
      self.failureReason = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Double.self, forKey: .evaluationPercentComplete)
    {
      self.evaluationPercentComplete = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Double.self, forKey: .reportGenerationPercentComplete)
    {
      self.reportGenerationPercentComplete = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Double.self, forKey: .reportUploadingPercentComplete)
    {
      self.reportUploadingPercentComplete = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .destinationGcsBucket) {
      self.destinationGcsBucket = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .auditReport) {
      self.auditReport = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.failureReason, forKey: .failureReason)
    try container.encode(self.evaluationPercentComplete, forKey: .evaluationPercentComplete)
    try container.encode(
      self.reportGenerationPercentComplete, forKey: .reportGenerationPercentComplete)
    try container.encode(
      self.reportUploadingPercentComplete, forKey: .reportUploadingPercentComplete)
    try container.encode(self.destinationGcsBucket, forKey: .destinationGcsBucket)
    try container.encode(self.auditReport, forKey: .auditReport)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.auditmanager.v1.ReportGenerationProgress"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
