// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Details about the current status of the report-generation process.
public struct ReportGenerationProgress: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Current state of execution for report generation.
  public var state: OperationState = OperationState()

  /// Output only. Reason for failure during the audit report generation process.
  /// This field is set only if the `OperationState` attribute is
  /// `OPERATION_STATE_FAILED`.
  public var failureReason: Swift.String = Swift.String()

  /// Progress of the evaluation process. The progress is
  /// defined in terms of percentage complete.
  public var evaluationPercentComplete: Swift.Double = Swift.Double()

  /// Report generation progress, defined in terms of percentage complete.
  /// Until evaluation is complete, this value is always `0`.
  public var reportGenerationPercentComplete: Swift.Double = Swift.Double()

  /// Report uploading progress, defined in terms of percentage complete.
  /// Until evaluation and report generation are complete, this value is always
  /// `0`.
  public var reportUploadingPercentComplete: Swift.Double = Swift.Double()

  /// Output only. Cloud Storage bucket where the audit report is uploaded to
  /// after the evaluation process is completed.
  public var destinationGcsBucket: Swift.String = Swift.String()

  /// Output only. Name of the audit report.
  public var auditReport: Swift.String = Swift.String()

  /// Initialize a new instance of `ReportGenerationProgress`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReportGenerationProgress().with { $0.state = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.auditmanager.v1.ReportGenerationProgress"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
