// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// An organization, folder, or project with its enrollment status.
public struct ResourceEnrollmentStatus: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. Name of the resource enrollment status, in one of the following
  /// formats:
  ///
  /// * `folders/{folder}/locations/{location}/resourceEnrollmentStatuses/{resource_enrollment_status}`
  /// * `projects/{project}/locations/{location}/resourceEnrollmentStatuses/{resource_enrollment_status}`
  /// * `organizations/{organization}/locations/{location}/resourceEnrollmentStatuses/{resource_enrollment_status}`
  public var name: Swift.String = Swift.String()

  /// Output only. Enrolled destination details for the organization, folder, or
  /// project.
  public var enrollment: Enrollment? = nil

  /// Output only. Deprecated. Whether the organization, folder, or project is
  /// enrolled. Use `enrollment_state` instead.
  @available(*, deprecated)
  public var enrolled: Swift.Bool = Swift.Bool()

  /// Output only. Display name for the organization, folder, or project.
  public var displayName: Swift.String = Swift.String()

  /// Output only. Enrollment state of the organization, folder, or project.
  public var enrollmentState: ResourceEnrollmentStatus.ResourceEnrollmentState =
    ResourceEnrollmentStatus.ResourceEnrollmentState()

  /// Initialize a new instance of `ResourceEnrollmentStatus`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ResourceEnrollmentStatus().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Different enrollment states of the resource and its parent.
  public enum ResourceEnrollmentState: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// The resource isn't enrolled.
    case notEnrolled
    /// The resource isn't enrolled but the parent is enrolled.
    case inherited
    /// The resource is enrolled.
    case enrolled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .notEnrolled: return 1
      case .inherited: return 2
      case .enrolled: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "RESOURCE_ENROLLMENT_STATE_UNSPECIFIED"
      case .notEnrolled: return "NOT_ENROLLED"
      case .inherited: return "INHERITED"
      case .enrolled: return "ENROLLED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ResourceEnrollmentState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "RESOURCE_ENROLLMENT_STATE_UNSPECIFIED": self = .unspecified
      case "NOT_ENROLLED": self = .notEnrolled
      case "INHERITED": self = .inherited
      case "ENROLLED": self = .enrolled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ResourceEnrollmentState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .notEnrolled
      case 2: self = .inherited
      case 3: self = .enrolled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .notEnrolled: return try container.encode(1)
      case .inherited: return try container.encode(2)
      case .enrolled: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.auditmanager.v1.ResourceEnrollmentStatus"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
