// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// State of an audit schedule.
///
/// - Note: Adding cases to this enumeration is not considered a breaking change.
///   Always include an `@unknown default:` case when switching over this type.
///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
///   expecting specific values to remain unparsed; future releases may promote
///   them to named cases.
public enum ScheduleState: Codable, Equatable, Sendable {
  /// Default value. This value is unused.
  case unspecified
  /// Schedule is active and will trigger runs.
  case active
  /// Schedule is paused and will not trigger runs.
  case paused
  /// Schedule end time has passed.
  case completed
  /// Schedule setup failed during creation or update.
  case failedSetup
  /// Schedule is in an error state due to persistent failure to trigger an
  /// audit. Manual intervention is required.
  case error
  /// Schedule has been marked for deletion by the user.
  case deleted
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific integer values in this case;
  ///   future releases may promote them to named enum cases.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific string literals in this case;
  ///   future releases may promote them to named enum cases.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .active: return 1
    case .paused: return 2
    case .completed: return 3
    case .failedSetup: return 4
    case .error: return 5
    case .deleted: return 6
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "SCHEDULE_STATE_UNSPECIFIED"
    case .active: return "SCHEDULE_STATE_ACTIVE"
    case .paused: return "SCHEDULE_STATE_PAUSED"
    case .completed: return "SCHEDULE_STATE_COMPLETED"
    case .failedSetup: return "SCHEDULE_STATE_FAILED_SETUP"
    case .error: return "SCHEDULE_STATE_ERROR"
    case .deleted: return "SCHEDULE_STATE_DELETED"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ScheduleState/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "SCHEDULE_STATE_UNSPECIFIED": self = .unspecified
    case "SCHEDULE_STATE_ACTIVE": self = .active
    case "SCHEDULE_STATE_PAUSED": self = .paused
    case "SCHEDULE_STATE_COMPLETED": self = .completed
    case "SCHEDULE_STATE_FAILED_SETUP": self = .failedSetup
    case "SCHEDULE_STATE_ERROR": self = .error
    case "SCHEDULE_STATE_DELETED": self = .deleted
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ScheduleState/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .active
    case 2: self = .paused
    case 3: self = .completed
    case 4: self = .failedSetup
    case 5: self = .error
    case 6: self = .deleted
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode("SCHEDULE_STATE_UNSPECIFIED")
    case .active: return try container.encode("SCHEDULE_STATE_ACTIVE")
    case .paused: return try container.encode("SCHEDULE_STATE_PAUSED")
    case .completed: return try container.encode("SCHEDULE_STATE_COMPLETED")
    case .failedSetup: return try container.encode("SCHEDULE_STATE_FAILED_SETUP")
    case .error: return try container.encode("SCHEDULE_STATE_ERROR")
    case .deleted: return try container.encode("SCHEDULE_STATE_DELETED")
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
