// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Timing and frequency parameters for recurring audit runs.
public struct ScheduleConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Date and time when the first audit run is triggered.
  /// Subsequent runs are based on this time and the chosen frequency.
  public var startTime: GoogleWKT.Timestamp? = nil

  /// Optional. Date that the schedule stops.
  /// If not specified, the schedule runs indefinitely.
  public var endTime: GoogleWKT.Timestamp? = nil

  /// Required. Frequency of audit runs.
  public var frequency: ScheduleConfig.Frequency = ScheduleConfig.Frequency()

  /// Optional. Time zone for the audit schedule in IANA format (for example,
  /// `America/New_York`). The time zone is used to interpret the `start_time`
  /// and the `end_time`, and to calculate subsequent run dates.
  /// If not specified, the time zone default is UTC.
  public var timeZone: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ScheduleConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ScheduleConfig().with { $0.startTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let startTime = CodingKeys(stringValue: "startTime")
    static let endTime = CodingKeys(stringValue: "endTime")
    static let frequency = CodingKeys(stringValue: "frequency")
    static let timeZone = CodingKeys(stringValue: "timeZone")

    static let _knownKeys: Set<Swift.String> = [
      "startTime",
      "endTime",
      "frequency",
      "timeZone",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.startTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .startTime)
    self.endTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .endTime)
    if let value = try container.decodeIfPresent(ScheduleConfig.Frequency.self, forKey: .frequency)
    {
      self.frequency = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .timeZone) {
      self.timeZone = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.startTime, forKey: .startTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)
    try container.encode(self.frequency, forKey: .frequency)
    try container.encode(self.timeZone, forKey: .timeZone)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Frequency of audit runs.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Frequency: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// The audit runs every day.
    case daily
    /// The audit runs weekly on the same day of the week as `start_time`.
    case weekly
    /// The audit runs monthly on the same day of the month as `start_time`.
    case monthly
    /// The audit runs quarterly (every 3 months) on the same
    /// day of the month as `start_time`.
    case quarterly
    /// The audit runs annually on the same month and day as `start_time`.
    case annually
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .daily: return 1
      case .weekly: return 2
      case .monthly: return 3
      case .quarterly: return 4
      case .annually: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "FREQUENCY_UNSPECIFIED"
      case .daily: return "DAILY"
      case .weekly: return "WEEKLY"
      case .monthly: return "MONTHLY"
      case .quarterly: return "QUARTERLY"
      case .annually: return "ANNUALLY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Frequency/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "FREQUENCY_UNSPECIFIED": self = .unspecified
      case "DAILY": self = .daily
      case "WEEKLY": self = .weekly
      case "MONTHLY": self = .monthly
      case "QUARTERLY": self = .quarterly
      case "ANNUALLY": self = .annually
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Frequency/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .daily
      case 2: self = .weekly
      case 3: self = .monthly
      case 4: self = .quarterly
      case 5: self = .annually
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("FREQUENCY_UNSPECIFIED")
      case .daily: return try container.encode("DAILY")
      case .weekly: return try container.encode("WEEKLY")
      case .monthly: return try container.encode("MONTHLY")
      case .quarterly: return try container.encode("QUARTERLY")
      case .annually: return try container.encode("ANNUALLY")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.auditmanager.v1.ScheduleConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
